version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./var/www/html:/usr/share/nginx/html
    restart: always
    networks:
      - shared
    depends_on:
      - stream

  stream:
    container_name: stream
    environment:
      - STREAM_URL=http://camera.buffalotrace.com/mjpg/video.mjpg
      - START_LIVE=1
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "9997:8080"
    volumes:
      - ./stream:/stream:rw
    stdin_open: true
    tty: true
    restart: always
    networks:
      - shared

networks:
  shared:
