[libraries]
androidx-activity-compose = "androidx.activity:activity-compose:1.8.0"
androidx-compose-bom = "androidx.compose:compose-bom:2024.09.00"
androidx-compose-material3 = "androidx.compose.material3:material3:material3"

[plugins]
android-application = "com.android.application:8.13.0"
kotlin-android = "org.jetbrains.kotlin.android:2.0.21"
kotlin-compose = "org.jetbrains.kotlin.plugin.compose:2.0.21"

