version: '3'

services:
  webrtc_tunnel:
    container_name: webrtc_tunnel
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: [
      "tunnel",
      "--no-autoupdate",
      "run",
      "--token",
      "$TUNNEL_TOKEN",
    ]
    networks:
      - shared
    restart: always

  webrtc:
    container_name: webrtc
    image: denoland/deno:1.43.6
    environment:
      - PWD=/code
    command: [
      "deno",
      "run",
      "--allow-net",
      "--allow-read",
      "/code/server.ts",
      "/code"
    ]
    volumes:
      - ./:/code:rw
    ports:
      - "5678:8080"
    networks:
      - shared
    restart: always

  client:
    container_name: client
    build:
      context: ./JSClient
      dockerfile: Dockerfile
    environment:
      - PASSWORD=$CLIENT_PASSWORD
      - WS_HOST=$WS_HOST
      - STREAM_URL=rtsp://admin:$STREAM_PASSWORD@192.168.0.108:80/cam/realmonitor?channel=1&subtype=0
    networks:
      - shared
    restart: always

networks:
  shared: