bios:
	curl -L \
	    https://ia902803.us.archive.org/view_archive.php?archive=/0/items/PlayStationBios/PlayStation%20Bios.zip\&file=SCPH-1000.bin \
		-o SCPH-1000.bin

setup-venv:
	python3 -m venv we2002 || true
	source ./we2002/bin/activate

page:
	open https://www.soccerdonna.de/en/

rom-patcher:
	https://www.marcrobledo.com/RomPatcher.js

patches:
	https://retroachievements.org/redirect?url=https%3A%2F%2Fgithub.com%2Franiedev%2Fretroachievements%2Fraw%2Fmain%2F14741-winning-eleven-2002-ps1%2FWe2002-ptbr.zip
	https://retroachievements.org/redirect?url=https%3A%2F%2Fgithub.com%2Franiedev%2Fretroachievements%2Fraw%2Fmain%2F14741-winning-eleven-2002-ps1%2FWe2002-eng.zip