version: '3'

services:
  nginx:
    container_name: ngrok
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./var/www/html:/usr/share/nginx/html
    restart: always
    networks:
      - shared
    depends_on:
      - youtube-dl
  youtube-dl:
    container_name: youtube-dl
    build:
      context: ./youtube-dl
      dockerfile: ./Dockerfile.youtube-dl
    ports:
      - "9998:8080"
    volumes:
      - ./youtube-dl:/youtube-dl:rw
    stdin_open: true
    tty: true
    restart: always
    networks:
      - shared

networks:
  shared:
