version: '3'

services:
  tunnel:
    container_name: tunnel
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: [
      "tunnel",
      "--no-autoupdate",
      "run",
      "--token",
      "$TUNNEL_TOKEN",
    ]
    networks:
      - shared
    restart: always
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./var/www/html:/usr/share/nginx/html
    restart: always
    networks:
      - shared
    depends_on:
      - youtube-dl
  youtube-dl:
    container_name: youtube-dl
    build:
      context: ./youtube-dl
      dockerfile: ./Dockerfile
    ports:
      - "9998:8080"
    volumes:
      - ./youtube-dl:/youtube-dl:rw
    stdin_open: true
    tty: true
    restart: always
    networks:
      - shared

  stream:
    container_name: stream
    environment:
      - HOST=$HOST
      - PORT=$PORT
      - STREAM_USER=$STREAM_USER
      - STREAM_PASSWORD=$STREAM_PASSWORD
      - ONVIF_USER=$ONVIF_USER
      - ONVIF_PASSWORD=$ONVIF_PASSWORD
    build:
      context: ./stream
      dockerfile: ./Dockerfile
    ports:
      - "9997:8080"
    volumes:
      - ./stream:/stream:rw
    stdin_open: true
    tty: true
    restart: always
    networks:
      - shared

  freeolingo:
    container_name: freeolingo
    build:
      context: ../Freeolingo/Server
      dockerfile: ./Dockerfile
    ports:
      - "9996:8080"
    stdin_open: true
    tty: true
    restart: always
    networks:
      - shared

networks:
  shared:
