version: '3.8'

services:
  simple-http-server:
    image: python:3.13.3-slim
    container_name: python-simple-server
    ports:
      - "8000:8000"
    volumes:
      - ../index.html:/app/index.html:ro
      - ../dist:/app/dist/:ro
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: ["python", "/app/src/main.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
